language: go
go:
- 1.7
git:
  depth: 9999999
env:
  global:
  - secure: gzX7Deqc8NcJRXaYHZjVcYYBiVV96sTk/ZgKRiG80YGixuGNjFmAUOlJ/OkGjaGBcoykKNSnVD3X1mZ2CuIsfr1c2md+aBHZf7TB10sarADqtmSmcWOloYF+9tzPi/3zy86KxPIyhcjQ3wuYA7cRqbKdktWWBn0vnwYv8tkyRc7JFKEM3KpUve7p71s1FwW00/sfm9PMU0G1yHRwOgWBQZtTTKFhzC6mEaD+bkUwe7wRY+eOHJSBVCb5bMHevEzxUfEWGsl2kBeKiP6krFiRm8AAm0tXxFJtWhUHBvVPTKhUqh5UpHeyaDPe/0beywvfWK4yNP586dRxbXp5MOgH/TAM7ak76dPrdQyqQAf37T9lGQ4lN2TkPGfIt8ne6SckcXtpIcmPfCzrj0kYZfycslU3ekz5vWDTXgU9xsfswpn5+E8SMjKbnnAZHD2WnnNAE20ZFsZ5RQukLd2vRpym0og9ApEbl45Fuh9pjjslrLoghkiJwjQl0vm3z/x9EjgZ7oRhS1P00BpM5HvANnixGrCC+D7QZh86wGeLCOanyykuySDh/DrtbO/u1Vl00IsuDA6xY/Yxe+Ua5oXy3kpzAT4URrW46bzCs57l59yCIJNhNmcsP9leMOCiPGVWo20r4qX5lRWyvUvaw6806H7BjOKk2O1/57eQhrn3n5lYYS0=
  - secure: bUXJ7pQejNsb+1aFCpvW3ITMVZAAxQZ5eVP5SqFmMCYMOzuVo4RtIluOqfKDwYUu0OHFbAblAZ7QpoAd5+WgVi4hV25otUKiGmudIQciFQqr9c3HmUwG6XldVqV6s8ufifK9eCuHTBqDNlM89aLg+fhJX5V/JhxomipIrwIpU8HFruasECHETroNWFE1+KJlkIy143vHlCDzC3QlSuX9gnyXiimf8w4y7jqKil3a1oMDxoXTZSwmaha4Naoi1Hj3/G6CU68togj+AzfR9Q/kqpZJsjGWM4wFopi8o+ueAZP19WfBBq1G1GlN23NYCv6dJgDnph9EZ8v6KliwYZWMK8zIMk42FNo6KzzaGG57PBQf7rUQSsevxIsUz8YT0S8IYSTVMznpDWrPkU3faB0D9eTl8p/w/ZpWitL1uwLlb1RmNVPW3JBCeH5VrL3OrkajHKgBjYgJtQyVYfDaNKgorzGtZZaAUdKH8vDBcveZbmXQf7TXjbMwng520hN9AVlK6q3pJ8tjfyMfdJZD6x+VhGU9Xvnc0XE+RlHWtyJZZOcqhCZfrnRKd0EncYtEYLUo5g6Q45rvV3HnZgifISM+SaO6jfKhOh1UpNJQlnbWa2wNkfZ1Qs8r70YEbSIwk6UvBqjuozqoHGpMmO4e8/5HWeIHZmvgPlO9AJ7zQVc9ipY=
  - secure: mYkrvDU4NS5iJisyS6rDI/fIUP0xqJLw/FPL2lnwNYmmyiPDw1KWxW0KIJPdp2OKyYEsol8CQKw3LkG7X2eNyhWSjOBs5uJm6+4+Jme3gStvdG8FOfHCGvrpumjxLZOidgZOUQuvroduFtgf1Mdd700L9lcgnlCLyXMU8VOdWVRfZhkDcgGz9dvvi3SJARM9lGz98E5evk/HQJrZ3uXiouvpwFzOAavzu3z34uHIX3Sgxp6MnuaZdI5Z4QAIjFf8OdBD2TrkvZNofuPvYqteeVDDkG/vqfvhR8zBGkHacJ1byHNuJ9VuyaigDxGhgSQ/CkJ4sCLTj+aBkUglbjX7jxu6EZUjnBiheH+zjjiuh9iuWoZsXeUAbh4kheEVvI8IrhKmMRuJeUmhfknzS8WZMCxL5lIR8PPglS477qUQ/GqbQGV0zmZf43hs/xyIp0Eymgs01HHuM/uQUk/qoZdGgLwSnE6OXZEjXeEVZQJdqubwHewu9U/VnqELCw2TNbq7eKGf+frVFNBf1xUKtkf+5iAb4WVNqmUTn6nY2DDtKlNhxGI4VA6LdY1rTB3aXtIcJ0H2YZdgKiGMmoaCovCWFJumqkDzSnc/frl7pRbtW6BM8d/mLe3CVd+Ic+vO8zSPiYfxAUrgEolQtzDuHjUf/HN3zcI4gMwqFjer9FjOJrU=
install:
- make get-deps
script: make cross-build
deploy:
- provider: script
  script: make deploy
  skip_cleanup: true
  on:
    repo: getcarina/dvm
    branch: rack-deploy
